- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Copy docker-compose to remote host
      copy:
        src: ./docker-compose.yml
        dest: /tmp/docker-compose

    - name: Start Docker containers
      shell: |
        ddocker-compose up --build
      args:
        chdir: /root/project
